#!/usr/bin/env python3
"""Small, explicit Git + B2 asset workflow. Python 3.11+."""

import argparse
from contextlib import contextmanager
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import sys
import tempfile
from urllib.parse import urlencode

from pathspec import GitIgnoreSpec


CONFIG = ".assets.json"
MANIFEST = "assets.lock.json"
LOCAL = ".assets-local"
CREDENTIALS = f"{LOCAL}/b2.json"
BEGIN = "# BEGIN bakery assets (generated by tools/assets.py ignore)"
END = "# END bakery assets"
HEX = re.compile(r"[0-9a-f]{64}\Z")
RESERVED = {".git", LOCAL, ".venv", "__pycache__"}
CONTROL = {CONFIG, MANIFEST, ".gitignore", ".gitattributes", ".gitmodules"}


class AssetError(Exception):
    pass


def safe_path(root, name, internal=False):
    parts = PurePosixPath(name).parts
    if (not name or "\\" in name or ":" in name or any(ord(c) < 32 for c in name)
            or name.startswith("/") or name != "/".join(parts)
            or any(p in {".", ".."} for p in parts)):
        raise AssetError(f"Unsafe project path: {name!r}")
    if not internal and (any(p in RESERVED for p in parts) or name in CONTROL
                         or any(p == ".env" or p.startswith(".env.") for p in parts)):
        raise AssetError(f"Reserved project path: {name}")
    path = root
    for i, part in enumerate(parts):
        path = path / part
        if path.is_symlink():
            raise AssetError(f"Symlinks are not supported: {name}")
        if path.exists() and i < len(parts) - 1 and not path.is_dir():
            raise AssetError(f"Parent is not a directory: {name}")
    return path


def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (ValueError, OSError) as exc:
        raise AssetError(f"Cannot read JSON: {path.name}") from exc


def atomic_write(path, content):
    fd, tmp = tempfile.mkstemp(prefix=".bakery-", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(tmp, path)
    finally:
        Path(tmp).unlink(missing_ok=True)


def write_json(path, value):
    atomic_write(path, json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n")


def fingerprint(path):
    if not path.exists():
        return None
    if not path.is_file() or path.is_symlink():
        raise AssetError(f"Not a regular file: {path}")
    before = path.stat()
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    after = path.stat()
    if (before.st_ino, before.st_size, before.st_mtime_ns, before.st_ctime_ns) != (
            after.st_ino, after.st_size, after.st_mtime_ns, after.st_ctime_ns):
        raise AssetError(f"File changed while reading: {path}")
    return {"sha256": digest.hexdigest(), "size": after.st_size}


def content(entry):
    return {key: entry[key] for key in ("sha256", "size")}


class Project:
    def __init__(self, root):
        self.root = Path(root).resolve()
        self.config_path = safe_path(self.root, CONFIG, internal=True)
        self.manifest_path = safe_path(self.root, MANIFEST, internal=True)
        self.local = safe_path(self.root, LOCAL, internal=True)
        self.state_path = safe_path(self.root, f"{LOCAL}/state.json", internal=True)
        self.config = read_json(self.config_path)
        c = self.config
        if (not isinstance(c, dict) or set(c) != {"version", "bucket", "prefix", "patterns"}
                or c["version"] != 1 or not isinstance(c["bucket"], str)
                or not isinstance(c["prefix"], str) or not c["prefix"].strip("/")
                or not isinstance(c["patterns"], list)
                or not all(isinstance(p, str) and p and "\n" not in p and "\r" not in p
                           for p in c["patterns"])):
            raise AssetError(f"Invalid {CONFIG}; expected version, bucket, prefix, patterns")
        self.spec = GitIgnoreSpec.from_lines(c["patterns"])
        self.manifest = read_json(self.manifest_path)
        if (not isinstance(self.manifest, dict) or set(self.manifest) != {"version", "files"}
                or self.manifest["version"] != 1 or not isinstance(self.manifest["files"], dict)):
            raise AssetError(f"Invalid {MANIFEST}")
        self.files = self.manifest["files"]
        for name, entry in self.files.items():
            safe_path(self.root, name)
            if (not isinstance(entry, dict)
                    or set(entry) != {"sha256", "size", "bucket", "key", "file_id"}
                    or not isinstance(entry["sha256"], str) or not HEX.fullmatch(entry["sha256"])
                    or type(entry["size"]) is not int or entry["size"] < 0
                    or not all(isinstance(entry[k], str) and entry[k] for k in ("bucket", "key", "file_id"))):
                raise AssetError(f"Invalid manifest entry: {name}")
        # Store only the last synchronized bytes for each local path, never history.
        self.state = read_json(self.state_path) if self.state_path.exists() else {}
        if not isinstance(self.state, dict):
            raise AssetError("Invalid local state")
        for name, entry in self.state.items():
            safe_path(self.root, name)
            if (not isinstance(entry, dict) or set(entry) != {"sha256", "size"}
                    or not isinstance(entry["sha256"], str) or not HEX.fullmatch(entry["sha256"])
                    or type(entry["size"]) is not int or entry["size"] < 0):
                raise AssetError("Invalid local state")
        self.original_config = self.config_path.read_bytes()
        self.original_manifest = self.manifest_path.read_bytes()

    def unchanged(self):
        if (self.config_path.read_bytes() != self.original_config
                or self.manifest_path.read_bytes() != self.original_manifest):
            raise AssetError("Configuration/manifest changed during operation; retry")

    def path(self, name):
        return safe_path(self.root, name)

    def scan(self):
        selected = {}
        for directory, dirs, names in os.walk(self.root, followlinks=False):
            dirs[:] = [d for d in dirs if d not in RESERVED]
            for name in names + [d for d in dirs if (Path(directory) / d).is_symlink()]:
                rel = (Path(directory) / name).relative_to(self.root).as_posix()
                if self.spec.match_file(rel):
                    selected[rel] = fingerprint(self.path(rel))
        return selected

    def git(self, *args, data=None):
        # Direct process invocation, no shell: preserve Git's NUL-delimited paths.
        result = subprocess.run(["git", "-C", str(self.root), *args],
                                input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if result.returncode not in (0, 1):
            raise AssetError("Git check failed; run inside the repository with Git installed")
        return result.stdout

    def check_git(self, names):
        tracked = set(self.git("ls-files", "-z").decode().split("\0"))
        overlap = tracked.intersection(names)
        if overlap:
            raise AssetError("Assets already tracked by Git: " + ", ".join(sorted(overlap)))
        if names:
            ignored = set(self.git("check-ignore", "--no-index", "-z", "--stdin",
                                   data=("\0".join(sorted(names)) + "\0").encode()).decode().split("\0"))
            missing = set(names) - ignored
            if missing:
                raise AssetError("Assets not ignored by Git (run 'ignore', check nested .gitignore): "
                                 + ", ".join(sorted(missing)))

    @contextmanager
    def locked(self):
        self.local.mkdir(exist_ok=True)
        lock = self.local / "lock"
        try:
            lock.mkdir()
        except FileExistsError as exc:
            raise AssetError(f"Another asset command is running. Stale lock? See docs: {lock}") from exc
        try:
            self.unchanged()
            yield
        finally:
            lock.rmdir()

    def save_state(self):
        write_json(self.state_path, self.state)

    def b2_store(self, config):
        self.check_git({CREDENTIALS})
        return B2Store(config, self.root)

    def ignore(self):
        path = safe_path(self.root, ".gitignore", internal=True)
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        block = BEGIN + "\n" + "\n".join(self.config["patterns"]) + "\n" + END
        if BEGIN in old or END in old:
            if old.count(BEGIN) != 1 or old.count(END) != 1 or old.index(BEGIN) > old.index(END):
                raise AssetError("Malformed generated .gitignore block")
            start, end = old.index(BEGIN), old.index(END) + len(END)
            new = old[:start] + block + old[end:]
        else:
            new = old.rstrip() + "\n\n" + block + "\n"
        # Keep internal files ignored even with broad negation rules.
        new = new.rstrip() + "\n"
        for rule in (f"/{LOCAL}/", ".venv/", "__pycache__/", ".env", ".env.*"):
            if rule not in new.splitlines()[new.splitlines().index(END) + 1:]:
                new += rule + "\n"
        atomic_write(path, new)
        print("Updated asset rules in .gitignore")

    def status(self, check=False):
        selected = self.scan()
        self.check_git(set(selected) | set(self.files))
        changes = 0
        for name in sorted(set(selected) | set(self.files)):
            entry = self.files.get(name)
            local = selected.get(name) if name in selected else fingerprint(self.path(name))
            if entry is None:
                label = "NEW"
            elif not self.spec.match_file(name):
                label = "EXCLUDED"
            elif local is None:
                label = "MISSING"
            elif local == content(entry):
                label = "OK"
            elif local == self.state.get(name):
                label = "NEEDS_PULL"
            else:
                label = "MODIFIED"
            if label != "OK":
                changes += 1
                print(f"{label:12} {name}")
        print(f"{len(self.files)} referenced, {len(selected)} local, {changes} differences")
        return int(check and changes > 0)

    def push(self, store_factory):
        selected = self.scan()
        self.check_git(set(selected) | set(self.files))
        missing = set(self.files) - set(selected)
        if missing:
            raise AssetError("Missing/excluded referenced assets; pull or explicitly forget first: "
                             + ", ".join(sorted(missing)))
        pending_pull = [n for n, e in self.files.items()
                        if selected[n] != content(e) and selected[n] == self.state.get(n)]
        if pending_pull:
            raise AssetError("Run pull after switching Git versions before push: " + ", ".join(pending_pull))
        new_files = dict(self.files)
        changed = [n for n in selected if n not in self.files or selected[n] != content(self.files[n])]
        store = store_factory(self.config) if changed else None
        for name in sorted(changed):
            print(f"PUSH         {name}", flush=True)
            expected = selected[name]
            # Upload an immutable snapshot: Blender may save the source while networking.
            with tempfile.TemporaryDirectory(prefix="upload-", dir=self.local) as tmp:
                snapshot = Path(tmp) / "content"
                shutil.copyfile(self.path(name), snapshot)
                if fingerprint(snapshot) != expected:
                    raise AssetError(f"File changed before upload: {name}")
                new_files[name] = store.ensure(snapshot, expected)
        if self.scan() != selected:
            raise AssetError("Assets changed during upload; manifest unchanged, retry push")
        self.unchanged()
        write_json(self.manifest_path, {"version": 1, "files": new_files})
        self.state.update(selected)
        self.save_state()
        print(f"Published {len(changed)} references; now commit the manifest with Git")

    def pull(self, store_factory):
        self.check_git(set(self.files))
        observed = {n: fingerprint(self.path(n)) for n in self.files}
        conflicts = [n for n, value in observed.items()
                     if value is not None and value != content(self.files[n]) and value != self.state.get(n)]
        if conflicts:
            raise AssetError("Unpublished/unknown local changes; move them aside or push on the correct Git version: "
                             + ", ".join(sorted(conflicts)))
        wanted = [n for n in self.files if observed[n] != content(self.files[n])]
        stores = {}
        with tempfile.TemporaryDirectory(prefix="download-", dir=self.local) as tmp:
            downloads = {}
            for i, name in enumerate(sorted(wanted)):
                entry = self.files[name]
                if entry["bucket"] not in stores:
                    stores[entry["bucket"]] = store_factory({**self.config, "bucket": entry["bucket"]})
                print(f"PULL         {name}", flush=True)
                staging = Path(tmp) / str(i)
                stores[entry["bucket"]].download(entry, staging)
                if fingerprint(staging) != content(entry):
                    raise AssetError(f"Download checksum mismatch: {name}")
                downloads[name] = staging
            self.unchanged()
            # Complete all downloads and recheck all destinations before installing any.
            for name, previous in observed.items():
                if fingerprint(self.path(name)) != previous:
                    raise AssetError(f"Local file changed during download: {name}")
            for name, staging in downloads.items():
                destination = self.path(name)
                destination.parent.mkdir(parents=True, exist_ok=True)
                if fingerprint(destination) != observed[name]:
                    raise AssetError(f"Local file changed during install: {name}")
                os.replace(staging, destination)
                self.state[name] = content(self.files[name])
                self.save_state()
        self.state.update({n: content(e) for n, e in self.files.items()})
        self.save_state()
        print(f"Restored {len(wanted)} files; unreferenced local files were kept")

    def forget(self, names):
        for name in names:
            self.path(name)
            if name not in self.files:
                raise AssetError(f"Not in manifest: {name}")
        self.unchanged()
        write_json(self.manifest_path, {"version": 1, "files": {
            n: entry for n, entry in self.files.items() if n not in names}})
        print(f"Forgot {len(set(names))} references; local files and B2 objects were kept")

    def share(self, name, hours, store_factory):
        if not 1 <= hours <= 168:
            raise AssetError("--hours must be between 1 and 168 (7 days)")
        path = self.path(name)
        if name not in self.files:
            raise AssetError(f"Not in manifest; push this asset first: {name}")
        entry = self.files[name]
        local = fingerprint(path)
        if local is not None and local != content(entry):
            raise AssetError(f"Local asset differs from manifest; push or pull before sharing: {name}")
        store = store_factory({**self.config, "bucket": entry["bucket"]})
        url = store.share(entry, hours * 3600)
        self.unchanged()
        return url


class B2Store:
    def __init__(self, config, root):
        from b2sdk.v2 import B2Api, InMemoryAccountInfo
        from b2sdk.v2.exception import B2Error
        self.config = config
        self.error_type = B2Error
        if not config["bucket"]:
            raise AssetError("Set bucket in .assets.json")
        credentials_path = safe_path(root, CREDENTIALS, internal=True)
        if not credentials_path.exists():
            raise AssetError(f"Create {CREDENTIALS} from tools/b2.example.json and fill in your B2 credentials")
        credentials = read_json(credentials_path)
        fields = {"application_key_id", "application_key"}
        if (not isinstance(credentials, dict) or set(credentials) != fields
                or not all(isinstance(credentials[k], str) and credentials[k].strip() for k in fields)):
            raise AssetError(f"Fill in application_key_id and application_key in {CREDENTIALS}")
        self.api = B2Api(InMemoryAccountInfo())
        try:
            self.api.authorize_account("production", credentials["application_key_id"], credentials["application_key"])
            self.bucket = self.api.get_bucket_by_name(config["bucket"])
        except B2Error as exc:
            raise AssetError(f"B2 authorization/bucket lookup failed ({type(exc).__name__})") from None

    def ensure(self, snapshot, expected):
        from b2sdk.v2.exception import FileNotPresent
        digest = expected["sha256"]
        key = f"{self.config['prefix'].strip('/')}/sha256/{digest[:2]}/{digest}"
        try:
            try:
                version = self.bucket.get_file_info_by_name(key)
            except FileNotPresent:
                version = self.bucket.upload_local_file(
                    local_file=str(snapshot), file_name=key,
                    file_info={"sha256": digest}, content_type="application/octet-stream")
            # A completed server-side version must exist before it can enter the manifest.
            version = self.api.get_file_info(version.id_)
            if (version.file_name != key or version.size != expected["size"]
                    or version.file_info.get("sha256") != digest):
                raise AssetError(f"B2 object metadata mismatch: {key}")
            return {**expected, "bucket": self.config["bucket"], "key": key, "file_id": version.id_}
        except self.error_type as exc:
            raise AssetError(f"B2 upload/verification failed ({type(exc).__name__})") from None

    def download(self, entry, destination):
        try:
            self.api.download_file_by_id(entry["file_id"]).save_to(str(destination))
        except self.error_type as exc:
            raise AssetError(f"B2 download failed ({type(exc).__name__})") from None

    def share(self, entry, seconds):
        if self.bucket.type_ != "allPrivate":
            raise AssetError("Temporary sharing requires a private bucket; public files remain publicly downloadable")
        try:
            # Download tokens work by name, so reject externally replaced objects.
            version = self.bucket.get_file_info_by_name(entry["key"])
            if (version.id_ != entry["file_id"] or version.size != entry["size"]
                    or version.file_info.get("sha256") != entry["sha256"]):
                raise AssetError("B2 object no longer matches this manifest version; cannot share by name")
            token = self.bucket.get_download_authorization(entry["key"], seconds)
            return self.bucket.get_download_url(entry["key"]) + "?" + urlencode({"Authorization": token})
        except self.error_type as exc:
            raise AssetError(f"B2 sharing failed ({type(exc).__name__}); check readFiles/shareFiles permissions") from None


def find_root(start):
    start = Path(start).resolve()
    for root in (start, *start.parents):
        if (root / CONFIG).exists():
            return root
    raise AssetError(f"Cannot find {CONFIG}; use --root PATH")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, help="project root (default: search from current directory)")
    commands = parser.add_subparsers(dest="command", required=True)
    status = commands.add_parser("status", help="hash local assets; no network")
    status.add_argument("--check", action="store_true", help="exit 1 if assets differ from manifest")
    commands.add_parser("ignore", help="sync selection rules to the generated .gitignore block")
    commands.add_parser("push", help="upload changed content, then atomically update manifest")
    commands.add_parser("pull", help="restore manifest versions without overwriting local changes")
    forget = commands.add_parser("forget", help="remove references only, never delete content")
    forget.add_argument("paths", nargs="+", help="exact project-relative paths")
    share = commands.add_parser("share", help="print a temporary download link for one asset")
    share.add_argument("path", help="exact project-relative path from the manifest")
    share.add_argument("--hours", type=int, default=1, help="link lifetime in hours: 1–168 (default: 1)")
    args = parser.parse_args(argv)
    try:
        project = Project(args.root or find_root(Path.cwd()))
        if args.command == "status":
            return project.status(args.check)
        with project.locked():
            if args.command == "ignore":
                project.ignore()
            elif args.command == "forget":
                project.forget(args.paths)
            elif args.command == "share":
                url = project.share(args.path, args.hours, project.b2_store)
                print(f"Download link valid for {args.hours} hour(s). Anyone with the link can download it.", file=sys.stderr)
                print(url)
            else:
                getattr(project, args.command)(project.b2_store)
        return 0
    except (AssetError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("Interrupted; rerun the command to retry", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
